### PR TITLE
Added travis

### PR DESCRIPTION
**Pull request by mohanprasathsj**

### CODE REVIEW

**Comment by riyadparvez** [comment]
Can you squish these three commits into one commit?
Google for git squish commit.

**Comment by mohanprasathsj** [comment]
Ok. Sure.

**Comment by mohanprasathsj** [comment]
Hi Riyad, 
I tried squashing, but old commits are still visible in my master branch, I am not sure this is how the squash will be. Let me know if any changes. Thanks:)

**Comment by riyadparvez** [comment]
Squash last n commits `git reset --soft HEAD~n && git commit`.

I can commit for you. But it's better, in the commit log you commit your own contribution.

**Pull request closed without merging**
